app/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse

from app import rest_views
from . import views

urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^$', views.landing, name='landing'),
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^userprofile/$', views.UserProfile.as_view(), name='userprofile'),
    # url(r'^userprofile/$', views.updateInfo, name='updateInfo'),
    url(r'^ajax/updatelocation/$', views.updatelocat, name='updatelocation'),
    url(r'^ajax/listFriend/$', views.listV.as_view(), name='list'),
]

wmap2017/urls.py
from django.conf.urls import url, include
from django.contrib.gis import admin
from rest_framework.authtoken import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-token-auth/', views.obtain_auth_token),
    url('', include('app.urls', namespace="app")),
    url(r'^rest/', include('app.rest_urls', namespace="rest")),
]

templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Friend Finder - Web Mapping 2017, Sample Application</title>

    {% load leaflet_tags %}
    {% load static %}

    {% leaflet_js plugins="forms" %}
    {% leaflet_css plugins="forms" %}

{#    <link rel="shortcut icon" href="{% static "Users/images/favicon.ico" %}" type="image/x-icon"/>#}
    <link rel="stylesheet" href="{% static "app/css/my_style.css" %}" type="text/css"/>

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="{% static "app/js/my_script.js" %}"></script>
</head>
<body>

<header>
    <table style="width: 100%">
        <tr>
            <td class="app-header" style="text-align: left; width: 55%;">
                Friend Finder
            </td>
            <td class="app-header-small" style="text-align: right; width: 45%;">
                {% if user.is_authenticated %}
                    {{ user.get_full_name }} ({{ user.username }}) |
                    <a href="{% url 'app:userprofile' %}">My Profile</a> |
                    <a href="{% url 'app:logout' %}">Log Out</a>
                {% else %}
                    <a href="{% url 'app:login' %}">Log In</a> |
                    <a href="{% url 'app:signup' %}">Sign Up</a>
                {% endif %}
            </td>
        </tr>
    </table>
</header>


<div id="content">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

templates/app/landing.html
{% extends "app/base.html" %}

{% load staticfiles %}

{% block content %}
    <p>Heya! You can share your location & track your friend's last stop in this app.</p>
{% endblock %}

templates/app/login.html
{% extends "app/base.html" %}

{% load staticfiles %}

{% block content %}
    <h3>Log In</h3>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p><span class="error">
                    <strong>{{ error|escape }}</strong>
                </span></p>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <p><span class="error">
                <strong>{{ error|escape }}</strong>
            </span></p>
        {% endfor %}
    {% endif %}


    {% if user.is_authenticated %}
        <p class="error">You are already logged in.</p>
    {% else %}

        <form method="post" action="{% url 'app:login' %}">
            {% csrf_token %}
            <table>
{#                <tr>#}
{#                    <td>{{ form.username.label_tag }}</td>#}
{#                    <td>{{ form.username }}</td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td>{{ form.password.label_tag }}</td>#}
{#                    <td>{{ form.password }}</td>#}
{#                </tr>#}
                {{ form.as_table }}
            </table>

            <input type="submit" value="Log In"/>
        </form>
    {% endif %}

{% endblock %}

templates/app/logout.html
{% extends "app/base.html" %}

{% load staticfiles %}

{% block content %}
    <p>Thank you for visiting. Come back soon.</p>
{% endblock %}

templates/app/signup.html
{% extends "app/base.html" %}

{% load staticfiles %}

{% block content %}
    <h3>Sign Up</h3>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p><span class="error">
                    <strong>{{ error|escape }}</strong>
                </span></p>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <p><span class="error">
                <strong>{{ error|escape }}</strong>
            </span></p>
        {% endfor %}
    {% endif %}

    {% if user.is_authenticated %}
        <p class="error">You are already logged in.</p>
    {% else %}

        <form method="post" action="{% url 'app:signup' %}">
            {% csrf_token %}
            <table>
                <tr>
                    <td>{{ form.username.label_tag }}</td>
                    <td>{{ form.username }}</td>
                </tr>
                <tr>
                    <td>{{ form.password.label_tag }}</td>
                    <td>{{ form.password }}</td>
                </tr>
                <tr>
                    <td>{{ form.password2.label_tag }}</td>
                    <td>{{ form.password2 }}</td>
                </tr>
                <tr>
                    <td>{{ form.first_name.label_tag }}</td>
                    <td>{{ form.first_name }}</td>
                </tr>
                <tr>
                    <td>{{ form.last_name.label_tag }}</td>
                    <td>{{ form.last_name }}</td>
                </tr>
                <tr>
                    <td>{{ form.email.label_tag }}</td>
                    <td>{{ form.email }}</td>
                </tr>
            </table>

            <input type="submit" value=""/>
        </form>
    {% endif %}

{% endblock %}

templates/app/user_profile.html
{% extends "app/base.html" %}

{% load staticfiles %}
{% load leaflet_tags %}

{% block content %}
    <h3>User Profile</h3>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p><span class="error">
                    <strong>{{ error|escape }}</strong>
                </span></p>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <p><span class="error">
                <strong>{{ error|escape }}</strong>
            </span></p>
        {% endfor %}
    {% endif %}

    {% if user.is_authenticated %}
        <form method="post" action="{% url 'app:userprofile' %}">
            {% csrf_token %}
            <table style="padding: 10px; width: 100%">
                <tr>
                    <td style="text-align: right; font-family: sans-serif, Arial; font-style: italic; font-weight: normal">
                        Username
                    </td>
                    <td style="font-family: sans-serif, Arial; font-style: italic; font-weight: bold">{{ object.username }}</td>
                </tr>
                <tr>
                    <td style="text-align: right; font-family: sans-serif, Arial; font-style: italic; font-weight: normal">
                        Last login
                    </td>
                    <td style="font-family: sans-serif, Arial; font-style: italic; font-weight: bold">{{ object.last_login }}</td>
                </tr>
                <tr>
                    <td style="text-align: right;">{{ form.first_name.label_tag }}</td>
                    <td>{{ form.first_name }}</td>
                </tr>
                <tr>
                    <td style="text-align: right;">{{ form.last_name.label_tag }}</td>
                    <td>{{ form.last_name }}</td>
                </tr>
                <tr>
                    <td style="text-align: right;">{{ form.email.label_tag }}</td>
                    <td>{{ form.email }}</td>
                </tr>
{#                <tr>#}
{#                    <td style="text-align: right;">{{ form.location.label_tag }}</td>#}
{#                    <td>{{ form.email }}</td>#}
{#                </tr>#}
                <tr>
                    <td style="text-align: right;"></td>
                    <td><input type="submit" value="Update Profile"/></td>
                </tr>
                {#                {{ form.as_table }}#}
            </table>
{#            <input type="submit" value="Update Profile"/>#}

        </form>
    {% else %}
        <p class="error">You are not logged in.</p>
    {% endif %}

    <p id="geom" style="visibility: hidden; display: none">{{ object.last_location.geojson }}</p>

    <script type="text/javascript" src="/static/app/js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="/static/app/js/ajaxHandling.js"></script>
    <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet.js"
   integrity="sha512-A7vV8IFfih/D732iSSKi20u/ooOfj/AGehOKq0f4vLT1Zr2Y+RX7C+w8A1gaSasGtRUZpF/NZgzSAu4/Gc41Lg=="
   crossorigin=""></script>
    <script>



    </script>

    <h3>Last known location</h3>
    <div style="text-align: center">
{#        {% leaflet_map "my_map" callback="map_init" %}#}
        <div id = 'mapD' style = "width:500px;height:500px;"></div>
        <input type = "button" id = "updateLastlocation" value = "update Last location"/>
        <input type = "button" id = "getFriend" value = "Print Friends"/>
    </div>
    {% block javascript %}
        {% csrf_token %}
        <script>
        var myLatLon, lat, long, data, map;

        map = L.map('mapD');
        map_init(map);

        function map_init(map, options) {
            //var geom = JSON.parse($("#geom").html());
{#            var myLatLon = L.latLng([geom.coordinates[1], geom.coordinates[0]]);#}
{##}
{#            geom = L.geoJson(geom);#}
{#            geom.addTo(map);#}
{##}
{#            map.setView(myLatLon, 16);#}

            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(showPosition);
            } else {
                x.innerHTML = "Geolocation is not supported by this browser.";
            }


            function showPosition(position) {

                var myStyle = {
                    "color": "#ff7800",
                    "weight": 5,
                    "opacity": 0.65
                };

                var myP = [{
                    "type": "Point",
                    "coordinates": [position.coords.latitude, position.coords.longitude]
                }];

                lat = position.coords.latitude;
                long = position.coords.longitude;

                myLatLon = L.latLng(lat, long);
                map.setView(myLatLon, 16);

                L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
                    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
                }).addTo(map);



                L.marker(myLatLon).addTo(map)
                    .bindPopup('you are here')
                    .openPopup();

{#                if(data != null){#}
{#                    for(var i = 0; i < data.length; i++){#}
{#                        myLatLon = L.latLng(data[i].geometry.coordinates[1], data[i].geometry.coordinates[0]);#}
{#                        console.log(myLatLon);#}
{#                        L.marker(myLatLon).addTo(map)#}
{#                        .bindPopup(data.properties.username)#}
{#                        .openPopup();#}
{#                     }#}
{#                }#}

                var myLines = [{
                    "type": "LineString",
                    "coordinates": [[lat, long], [lat + 10, long + 10], [lat + 12, long + 12]]
                }, {
                    "type": "LineString",
                    "coordinates": [[lat, long], [lat + 10, long + 10], [lat + 12, long + 12]]
                }];
            }

        }

        $("#updateLastlocation").click(function(){
            console.log(lat,long);
{#            geojson = { "type": "Feature",#}
{#                    "geometry": {"type": "Point", "coordinates": [lat, long]}};#}

            $.ajax({
                type:'POST',
                url:'/ajax/updatelocation/',
                data: {"lat":lat, "long":long},
                datatype:'json',
                success: function(data){
                    alert('Update Successfully');
                }
            });

            map.remove(map);

            map = L.map('mapD');
            map_init(map);

        });

        $("#getFriend").click(function(){
            console.log('try get some friends');
            $.ajax({
                type:'GET',
                url:'/ajax/listFriend/',
                success: function(data){
                    console.log(data.features);
                    displayFriend(data.features);
                }
            });
        });

        function displayFriend(data){
            var pos;
            var time;
            console.log(data[1]);
            for(var i = 0; i < data.length; i++){
                pos = L.latLng(data[i].geometry.coordinates[1], data[i].geometry.coordinates[0]);
                time = new Date(data[i].properties.last_login)
                L.marker(pos).addTo(map)
                    .bindPopup(data[i].properties.username+'\nLast login:'+time)
                    .openPopup();
            }
        }
        </script>
    {% endblock %}
    <div>
{#         <form method="post" action="{% url 'app:updateInfo' %}">#}
{#                {% csrf_token %}#}
{#                <table>#}
{#                    <tr>#}
{#                        <td>{{ form.lat.label_tag }}</td>#}
{#                        <td>{{ form.lat }}</td>#}
{#                    </tr>#}
{#                    <tr>#}
{#                        <td>{{ form.long.label_tag }}</td>#}
{#                        <td>{{ form.long }}</td>#}
{#                    </tr>#}
{#                    {{ form.as_table }}#}
{#                </table>#}
{#                <input type="submit" value="Update Location"/>#}
{#        </form>#}
    </div>


{% endblock %}